use Pokemon
select name from Trainer where hometown = 'Blue City';
select name from Trainer where hometown = "Brown City" or hometown = "Rainbow City";
select name, hometown from Trainer where name like 'A%' or name like 'E%' or name like 'I%' or name like 'O%' or name like 'U%';
select name from Pokemon where type = 'Water';
select distinct type from Pokemon;
select name from Pokemon order by name;
select name from Pokemon where name like '%s';
select name from Pokemon where name like '%e%s';
select name from Pokemon where name like 'a%' or name like 'e%' or name like 'i%' or name like 'o%' or name like 'u%';
select type, count(*) as '#Pokemon' from Pokemon group by type;
select nickname from CatchedPokemon order by level desc limit 3;
select avg(level) as 'average level' from CatchedPokemon;
select max(level) - min(level) as 'maxlevel - minlevel' from CatchedPokemon;
select count(*) as '#of b~e' from Pokemon where name between 'b%' and 'f%';
select count(*) as '#Pokemon' from Pokemon where type not in ('fire', 'grass', 'water', 'electonic');
select Trainer.name as 'Trainer', Pokemon.name as 'Pokemon', nickname from Trainer, CatchedPokemon, Pokemon where nickname like '% %' and owner_id = Trainer.id and pid = Pokemon.id;
select Trainer.name as 'Trainer' from Trainer, CatchedPokemon, Pokemon where pid = Pokemon.id and type = 'psychic' and owner_id = Trainer.id;
select Trainer.name, hometown from Trainer, CatchedPokemon where Trainer.id = owner_id group by owner_id order by avg(level) desc limit 3;
select Trainer.name, count(*) as '#Pokemon' from Trainer, CatchedPokemon where Trainer.id = owner_id group by owner_id order by count(*) desc, Trainer.name desc;
select Pokemon.name as 'Pokemon', level from Gym, Trainer, CatchedPokemon, Pokemon where leader_id = Trainer.id and Trainer.id = owner_id and pid = Pokemon.id and city = 'Sangnok City' order by level;
select Pokemon.name, count(pid) from Pokemon left join CatchedPokemon on Pokemon.id = pid group by Pokemon.name order by count(pid) desc;
select Pokemon.name from Pokemon, Evolution where after_id = Pokemon.id and before_id in (select Pokemon.id from Pokemon, Evolution where after_id = Pokemon.id and before_id in (select Pokemon.id from Pokemon where name = 'Charmander') );
select distinct Pokemon.name from Pokemon, CatchedPokemon where Pokemon.id <= 30 and Pokemon.id in (select pid from CatchedPokemon) order by Pokemon.name;
select Trainer.name, type from Trainer, Pokemon, CatchedPokemon where pid = Pokemon.id and Trainer.id = owner_id group by Trainer.name having count(distinct type) = 1;
select Trainer.name, Pokemon.type, count(*) as '#Pokemon' from Trainer, CatchedPokemon, Pokemon where Trainer.id = owner_id and pid = Pokemon.id group by Trainer.name, Pokemon.type;
select Trainer.name as 'Trainer', Pokemon.name as 'Pokemon', count(pid) as 'count' from Trainer, Pokemon, CatchedPokemon where Trainer.id = owner_id and pid = Pokemon.id group by Trainer.name having count(distinct pid) = 1;
select Trainer.name, Gym.city from Trainer, Gym where leader_id = Trainer.id and Trainer.name not in ( select Trainer.name from Trainer, Pokemon, CatchedPokemon where Trainer.id = owner_id and Pokemon.id = pid group by Trainer.name having count(distinct type) = 1 );
select Trainer.name, sum(level) from Trainer, Gym left join CatchedPokemon on level >= 50 and leader_id = owner_id where leader_id = Trainer.id group by Trainer.name;
select Pokemon.name from Pokemon, Trainer, CatchedPokemon where Trainer.id = owner_id and hometown = 'Sangnok City' and Pokemon.id = pid and Pokemon.id in ( select Pokemon.id from Pokemon, Trainer, CatchedPokemon where Trainer.id = owner_id and hometown = 'Blue City' and Pokemon.id = pid );
select distinct Pokemon.name from Pokemon, Evolution where Pokemon.id not in (select before_id from Evolution ) and Pokemon.id in (select after_id from Evolution);
